helm:
  repositories:
    - name: "jetstack"
      url: "https://charts.jetstack.io"

  releases:
    - name: "cert-manager"
      chart: "jetstack/cert-manager"
      namespace: "{{ vars.namespace }}"
      version: "v1.16.2"
      values:
        - "values/**/*.{yml,yml.j2,yaml,yaml.j2}"